{
 "title": "GPU",
 "description": "GPU dashboard for nvidia metrics ",
 "tags": [
  "gpu",
  "cluster",
  "hardware",
  "infrastructure"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "label_values(nvidia_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Driver Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nvidia_driver_info{instance=\"$host\",job=\"gpu\"}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nvidia_utilization_gpu{instance=\"$host\",job=\"gpu\"}) / sum(nvidia_device_count{instance=\"$host\",job=\"gpu\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nvidia_utilization_memory{instance=\"$host\",job=\"gpu\"}) / sum(nvidia_device_count{instance=\"$host\",job=\"gpu\"})"
    }
   ]
  },
  {
   "title": "GPU Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nvidia_utilization_gpu{instance=\"$host\",job=\"gpu\"}",
     "legendFormat": "gpu{{minor}}"
    }
   ]
  },
  {
   "title": "Memory Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nvidia_utilization_memory{instance=\"$host\",job=\"gpu\"}",
     "legendFormat": "gpu{{minor}}"
    }
   ]
  },
  {
   "title": "# GPUs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(nvidia_device_count{instance=\"$host\",job=\"gpu\"})"
    }
   ]
  },
  {
   "title": "Memory Used (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(nvidia_memory_used{instance=\"$host\",job=\"gpu\"} / nvidia_memory_total{instance=\"$host\",job=\"gpu\"}) * 100",
     "legendFormat": "gpu{{minor}}"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "expr": "nvidia_power_usage{instance=\"$host\",job=\"gpu\"}",
     "legendFormat": " gpu{{minor}}"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nvidia_fanspeed{instance=\"$host\",job=\"gpu\"}",
     "legendFormat": " gpu{{minor}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 13 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "nvidia_temperatures{instance=\"$host\",job=\"gpu\"}",
     "legendFormat": "gpu{{minor}}"
    }
   ]
  }
 ]
}